### ISSUE TITLE
create readme.md file

### ISSUE THREAD

**Issue by aanchal22** [nyu-devops-squad/shopcarts#3]
**As a** developer
**I need** to create a README.md file
**So that** users will know how it works.

**Details & Assumptions:** 
* Create a README.md file and make sure that you give instructions on what calls are available and what inputs they expect and how to run and test your code so that users will know how it works.

**Acceptance Criteria:**

```gherkin
Given the README.md file
When the users try to use any service of the shopcarts
Then they should refer to the README.md file and find out how to run the code/call the relevant API
```

**Comment by wyf2154** [comment]
**As a** developer
**I need** to create a README.md file
**So that** users will know how it works.

**Details & Assumptions:** 
* Create a README.md file and make sure that you give instructions on what calls are available and what inputs they expect and how to run and test your code so that users will know how it works.

**Acceptance Criteria:**

```gherkin
Given the README.md file
When the users try to use any service of the shopcarts
Then they should refer to the README.md file and find out how to run the code/call the relevant API
```

**Comment by helloyxy** [comment]
hi, I think this issue's lable should be documentation?

**Comment by wyf2154** [comment]
I'm trying to label all stories which will deliver costomer value as enhancement, but documentation is fine too. Let's just leave as it is, we can change the label later when needed
